# This file was generated by GoReleaser. DO NOT EDIT.
cask "cognitive-os" do
  version "0.29.29"

  on_macos do
    on_intel do
      sha256 "d7248fb135ab89508104c775a64c21427d3f791db646f9193619d9ce63383e41"
      url "https://github.com/Luum-Home/luum-cognitive-os/releases/download/v#{version}/cognitive-os_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "04c24761323eec6ec7a6e2ac5b91dfbaee0b4573454b31ae5ce44f412cff365d"
      url "https://github.com/Luum-Home/luum-cognitive-os/releases/download/v#{version}/cognitive-os_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fb69f99a4de11468dc4cc44bc35e29e13cde6c932efc1cfea3d65aa771ae4898"
      url "https://github.com/Luum-Home/luum-cognitive-os/releases/download/v#{version}/cognitive-os_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "70338bf3bfb7c9d42dd97c3009f1975edc8c86153cb5655eee158d6b13348cfb"
      url "https://github.com/Luum-Home/luum-cognitive-os/releases/download/v#{version}/cognitive-os_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cognitive-os"
  desc "Portable AI Agent Operating System — memory, quality gates, self-healing"
  homepage "https://github.com/Luum-Home/luum-cognitive-os"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cos"

  # No zap stanza required

  caveats <<~EOS
    Cognitive OS is distributed under FSL-1.1-MIT, which is source-available and not represented by a Homebrew Cask SPDX license stanza. See LICENSE in the archive.
  EOS
end
