# This file was generated by GoReleaser. DO NOT EDIT.
cask "cognitive-os" do
  version "0.29.14"

  on_macos do
    on_intel do
      sha256 "ecfb46a11e2f359a9605ec34ca3ae29c427b5ccc44b7fb2080312a36b8021a4d"
      url "https://github.com/Luum-Home/luum-cognitive-os/releases/download/v#{version}/cognitive-os_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6cc5810176fdee7ef4f3f11feda20e65ffd33ea502ee4a10c72db2e7b2e5be2c"
      url "https://github.com/Luum-Home/luum-cognitive-os/releases/download/v#{version}/cognitive-os_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d37cc155536ca2d10a89b21635012bf8ab756eeb00a7c97a06a926cac1326e47"
      url "https://github.com/Luum-Home/luum-cognitive-os/releases/download/v#{version}/cognitive-os_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e5ee525463a3f27ac97449a4bfc1d3f2a686e118b5702c21b546201cb6eab41c"
      url "https://github.com/Luum-Home/luum-cognitive-os/releases/download/v#{version}/cognitive-os_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cognitive-os"
  desc "Portable AI Agent Operating System — memory, quality gates, self-healing"
  homepage "https://github.com/Luum-Home/luum-cognitive-os"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cos"

  # No zap stanza required

  caveats <<~EOS
    Cognitive OS is distributed under FSL-1.1-MIT, which is source-available and not represented by a Homebrew Cask SPDX license stanza. See LICENSE in the archive.
  EOS
end
