# This file was generated by GoReleaser. DO NOT EDIT.
cask "cognitive-os" do
  version "0.29.35"

  on_macos do
    on_intel do
      sha256 "9d41dee04a73bb66e6824ada98efd003bccfe8f8e6160fd8886452cbb4adec45"
      url "https://github.com/Luum-Home/luum-cognitive-os/releases/download/v#{version}/cognitive-os_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f07670a5333cca8b6b7bf714359fdbc6432bbc3506a95722a7063c101568894c"
      url "https://github.com/Luum-Home/luum-cognitive-os/releases/download/v#{version}/cognitive-os_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bc7a6045b9fa1dccfc5ee6feb939fa32c1482a98b50282f0a70a8159edafa359"
      url "https://github.com/Luum-Home/luum-cognitive-os/releases/download/v#{version}/cognitive-os_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f7eee9c62a313e4d0bce2b08672af44e0442c5f8128f4bb494610e1db9dce5d3"
      url "https://github.com/Luum-Home/luum-cognitive-os/releases/download/v#{version}/cognitive-os_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cognitive-os"
  desc "Portable AI Agent Operating System — memory, quality gates, self-healing"
  homepage "https://github.com/Luum-Home/luum-cognitive-os"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cos"

  # No zap stanza required

  caveats <<~EOS
    Cognitive OS is distributed under FSL-1.1-MIT, which is source-available and not represented by a Homebrew Cask SPDX license stanza. See LICENSE in the archive.
  EOS
end
